bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('account/', include('account.urls')),
                  path('social-auth/', include('social_django.urls', namespace='social')),
                  path('images/', include('images.urls', )),
              ] + static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from . import views

app_name = 'images'
urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('like/', views.image_like, name='like'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
</head>
<body>
<div id="header">
    <span class="logo">Bookmarks</span>
    {% if request.user.is_authenticated %}
        <ul class="menu">
            <li {% if section == "dashboard" %}class="selected"{% endif %}>
                <a href="{% url "dashboard" %}">My dashboard</a>
            </li>
            <li {% if section == "images" %}class="selected"{% endif %}>
                <a href="{% url 'images:create' %}">Images</a>
            </li>
            <li {% if section == "people" %}class="selected"{% endif %}>
                <a href="{% url 'user_list' %}">People</a>
            </li>
        </ul>
    {% endif %}
    <span class="user">
{% if request.user.is_authenticated %}
    Hello {{ request.user.first_name }},
    <a href="{% url "logout" %}">Logout</a>
{% else %}
    <a href="{% url "login" %}">Log-in</a>
{% endif %}
</span>
</div>
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li class="{{ message.tags }}">{{ message|safe }}<a href="{% url 'dashboard' %}" class="close">x</a></li>
        {% endfor %}
    </ul>
{% endif %}
<div id="content">
    {% block content %}
    {% endblock %}
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
<script>
    var csrftoken = Cookies.get('csrftoken');

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });
    $(document).ready(function () {
        {% block domready %}
        {% endblock %}
    });
</script>
</body>
</html>